name: CD Yandex
on:
    workflow_dispatch:

jobs:
    build-and-push-to-yc:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Build docker image
              run: docker build . --file Dockerfile --tag cr.yandex/${{secrets.YC_REGISTRY_ID }}/rickandmorty:latest
            - name: Login to YC Registry
              uses: docker/login-action@v3.0.0
              with:
                registry: cr.yandex
                username: json_key
                password: ${{ secrets.YC_KEYS }}
            - name: Push tag to YC Registry
              run: docker push cr.yandex/${{ secrets.YC_REGISTRY_ID }}/jstore:latest 
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        needs: [build-and-push-to-yc]
        steps:
          - name: Deploy serverless container
            uses: yc-actions/yc-sls-container-deploy@v1
            with:
              yc-sa-json-credentials: ${{ secrets.YC_KEYS }}
              container-name: ${{ secrets.YC_CONTAINER_NAME }}
              folder-id: ${{ secrets.YC_FOLDER_ID }}
              revision-image-url: cr.yandex/${{ secrets.YC_REGISTRY_ID }}/jstore:latest
              revision-service-account-id: ${{ secrets.YC_SA_ID }}
              
